default_workflow = "data/default_workflow.yml"

badges = [
    "github",
    "crates.io",
    "docs.rs",
    "github-actions",
]

job_name = "CI"
license = "MIT/Apache-2.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
